### ISSUE TITLE
希望能在paratranz上创建一份本项目的拷贝

### ISSUE THREAD

**Issue by diskrubbish** [sffxzzp/Starbound-Chinese#34]
首先非常感谢星核汉化组为我们stb玩家带来的优质汉化！

paratranz有名词解释，翻译记忆，同游戏的文本之间可以相互借鉴，并且能很方便的统一译名。

现在paratranz上开设了[starbound专区](https://paratranz.cn/projects?game=stb)，只需要上传特制的patch，就能将jsonpatch中的文本导入到网站上，并在翻译后输出格式规范的patch。

在翻译mod的过程中，我和我们组员发现想要参考原版名词的翻译极其困难，原来的starbound中文论坛已经关闭，参考帖子也一并丢失，而灰机wiki上的资料又过失而不准确，最后想到参考星核的名词，就产生了想要在paratranz上创建本项目镜像的想法。

如果允许的话，我会在创建项目后将项目的持有者交给星核组，并将在过程中用到的程序代码开源，而且合鸟汉化组也很想为stb原版的翻译进行考证和进一步修正，比如hokucide，其实是玩了北斋的梗（音同hokusai），我们组认为这把刀可以翻译成北灾。

**Comment by sffxzzp** [comment]
已加 Steam 好友，详聊。
